### ISSUE TITLE
individual_id? or metadata feed for COMPASSContainerFromGatingSet

### ISSUE THREAD

**Issue by mimisikai** [RGLab/COMPASS#60] opened 2018-04-09 22:49 UTC
I cannot catch up how to input the metadata for COMPASSContainerFromGatingSet. Can you give a example for working on GatingSet? 
I get bunch of missing warnings when I code as:
COMPASSContainerFromGatingSet(gs = gs_man, "CD154",individual_id = pData(gs_man)$name)

Extracting cell counts
Fetching CD154
Some columns not found in metadata
Expected: name P1_S003_V1_CD154_ICS_Enr.fcsExpected: name P1_S003_V1_CD154_ICS_Pre.fcsExpected: name P1_S003_V3_CD154_ICS_Enr.fcsExpected: name P1_S003_V3_CD154_ICS_Pre.fcsExpected: name P1_S003_V4_CD154_ICS_Enr.fcsExpected: name P1_S003_V4_CD154_ICS_Pre.fcsExpected: name P1_S005_V1_CD154_ICS_Enr.fcsExpected: name P1_S005_V1_CD154_ICS_Pre.fcsExpected: name P1_S005_V3_CD154_ICS_Enr.fcsExpected: name P1_S005_V3_CD154_ICS_Pre.fcsExpected: name P1_S005_V4_CD154_ICS_Enr.fcsExpected: name P1_S005_V4_CD154_ICS_Pre.fcsExpected: name P1_S007_V1_CD154_ICS_Enr.fcsExpected: name P1_S007_V1_CD154_ICS_Pre.fcsExpected: name P1_S007_V3_CD154_ICS_Enr.fcsExpected: name P1_S007_V3_CD154_ICS_Pre.fcsExpected: name P1_S007_V4_CD154_ICS_Enr.fcsExpected: name P1_S007_V4_CD154_ICS_Pre.fcsExpected: name P1_S009_V1_CD154_ICS_Enr.fcsExpected: name P1_S009_V1_CD154_ICS_Pre.fcsExpected: name P1_S009_V3_CD154_ICS_Enr.fcsExpected: name P1_S009_V3_CD154_ICS_Pre.fcsExpected: name P1_S009_V4_CD154_ICS_Enr.fcsExpected: n... <truncated>
Missing: P1_S003_V1_CD154_ICS_Enr.fcs
Missing: P1_S003_V1_CD154_ICS_Pre.fcs
Missing: P1_S003_V3_CD154_ICS_Enr.fcs

**Comment by gfinak** [comment] 2018-04-09 23:04
I suggest creating a compass container "by hand". Extracting the different pieces you need and build the container using the COMPASSContainer constructor.
To extract the single cell data use the getSingleCellExpression() method on the gating set.
The reason I suggest this is that the API you are using is not very well supported. This way you will  be able to see exactly what and if something fails.
Best
Greg

**Comment by mimisikai** [comment] 2018-04-10 18:44
My data isn't single cell expression. It's normal FACS data, I want to utilize poly-function features as 7 cytokines included in my panel, I wonder the any cytokines "combinations". To be honestly, I cannot reproduce my data through your documents. Here are some reasons: 
1. In your stimulated data, those are intensity, but my data is %. I guess I can use the %. 
2. Based on intensity, I assume COMPASS will easily be able to calculate the combinations among any cytokines. But, if the % as the input, is that ok?
3. If COMPASS works on % that produce by flow data, can you give an example to construct COMPASSContainer from these conventional flow data? 
Thanks,
Joe

**Comment by gfinak** [comment] 2018-04-10 19:00
I'm well aware of what FACS data is. The *getSingleCellExpression* API is in the *flowWorkspace* package and fetches the event-level (single-cell-level) data from the GatingSet that is needed to construct the cell counts of the different polyfunctional cell populations defined by the markers.
To address your questions:
1. No you can't use %. You need cell counts. That's what the *getSingleCellExpression* API together with the *COMPASSContainer* object will compute for you.
2. You can't use %. COMPASS will compute the cell counts of different combinations for you from the input. 
3. COMPASS doesn't work on %.

Read the documentation for *COMPASSContainer*, read the documentation for *getSingleCellExpression*. To construct a COMPASSContainer you need at a minimum:

```
 data: A list of matrices. Each matrix ‘M_i’ is made up of ‘N_i’
          cells by ‘K’ markers; for example, it could be the intensity
          information from an intracellular cytokine experiment. Each
          element of the list should be named; this name denotes which
          sample the cell intensities were measured from.

  counts: A named integer vector of the cell counts(of the parent
          population) for each sample in ‘data’.

    meta: A ‘data.frame’ of metadata, describing the individuals in the
          experiment. Each row in ‘meta’ should correspond to a row in
          ‘data’. There should be one row for each sample; i.e., one
          row for each element of ‘data’.

individual_id: The name of the vector in ‘meta’ that denotes the
          individuals from which samples were drawn.

sample_id: The name of the vector in ‘meta’ that denotes the samples.
          This vector should contain all of the names in the ‘data’
          input.
```
`data` is what is returned from the `getSingleCellExpression` API.

**Comment by gfinak** [comment] 2018-04-11 16:37
I'm closing this issue for now, feel free to comment here if you run into problems using the metadata.

**Closed by gfinak** 2018-04-11 16:37 UTC

**Comment by mimisikai** [comment] 2018-04-19 18:29
Hi Greg,
I've encountered some problems with COMPASS, even if I go through the
documentations.
1. I may not fully understand the individual_id and sample_id. In my mind,
the individual_id is FCS file name, and sample_id is sample labeling,
However, when I put those into COMPASSContainer, the warning msgs:

> cc= COMPASSContainer(data = ll, counts = counts, meta = meta, individual_id = "New", sample_id = "PTID")Warning messages:1: In COMPASSContainer(data = ll, counts = counts, meta = meta, individual_id = "New",  :  There appear to be negative intensities in the 'data' supplied.2: In check_meta(data, counts, meta, individual_id, sample_id) :  There are sample ids in 'data' that are not available in the metadata passed. These sample ids are: P1_S003_V1_CD154_ICS_Enr.fcs, P1_S003_V1_CD154_ICS_Pre.fcs, P1_S003_V3_CD154_ICS_Enr.fcs, P1_S003_V3_CD154_ICS_Pre.fcs, P1_S003_V4_CD154_ICS_Enr.fcs, P1_S003_V4_CD154_ICS_Pre.fcs, P1_S005_V1_CD154_ICS_Enr.fcs, P1_S005_V1_CD154_ICS_Pre.fcs, P1_S005_V3_CD154_ICS_Enr.fcs, P1_S005_V3_CD154_ICS_Pre.fcs, P1_S005_V4_CD154_ICS_Enr.fcs, P1_S005_V4_CD154_ICS_Pre.fcs, P1_S007_V1_CD154_ICS_Enr.fcs, P1_S007_V1_CD154_ICS_Pre.fcs, P1_S007_V3_CD154_ICS_Enr.fcs, P1_S007_V3_CD154_ICS_Pre.fcs, P1_S007_V4_CD154_ICS_Enr.fcs, P1_S007_V4_CD154_ICS_Pre.fcs, P1_S009_V1_CD154_ICS_Enr.fcs, P1_S009_V1_CD154_ICS_Pre.fcs, P1_S009_V3_CD154_ICS_Enr.fcs, P1_S009_V3_CD154_ICS_Pre.fcs, P1_S009_V4_CD154_ICS_Enr.fcs, P1_S009_V4_CD154_ICS_Pre.fcs, P1_S014_V3_CD154_ICS_Enr.fcs, P1_S014_V3_CD154_ICS_Pre.fcs, P1_S027_V1_CD154_ICS_Enr.fcs, P1_S027_V1_CD154_ICS_Pre.fcs, P1_S027_V3_CD154_ICS_Enr.fcs, P1_S027_V3_CD154_ICS_Pre.fcs,  [... truncated]


The data shows as:

ll[[1]]        Comp-PE-Cy7-A Comp-PerCP-Cy5-5-A Comp-APC-Cy7-A
Comp-FITC-A Comp-Alexa Fluor 647-A Comp-Alexa Fluor 700-A
   [1,]      93.39796            0.00000        0.00000    97.60947
           62.82008               72.60860
   [2,]      93.38947            0.00000       74.15135     0.00000
            0.00000                0.00000
   [3,]       0.00000            0.00000        0.00000     0.00000
           62.18153                0.00000
   [4,]      93.70161            0.00000        0.00000     0.00000
            0.00000               83.09550
   [5,]       0.00000            0.00000       74.96181    92.62379
           56.73948               76.36242
   [6,]      93.36813            0.00000       62.89649     0.00000
            0.00000                0.00000
   [7,]       0.00000            0.00000       69.82207     0.00000
            0.00000                0.00000
   [8,]      92.86130           98.01012        0.00000     0.00000
            0.00000               71.22775
   [9,]       0.00000            0.00000       63.51693     0.00000
          116.96052                0.00000
  [10,]       0.00000           98.38001       76.30012    88.96437
            0.00000               80.30758


The meta as:

New        PTID Subject Visit Assay Enrichment
1 P1_S003_V1_CD154_ICS_Enr.fcs S003_V1_Enr    S003    V1 CD154        Enr
2 P1_S003_V1_CD154_ICS_Pre.fcs S003_V1_Pre    S003    V1 CD154        Pre
3 P1_S003_V3_CD154_ICS_Enr.fcs S003_V3_Enr    S003    V3 CD154        Enr
4 P1_S003_V3_CD154_ICS_Pre.fcs S003_V3_Pre    S003    V3 CD154        Pre
5 P1_S003_V4_CD154_ICS_Enr.fcs S003_V4_Enr    S003    V4 CD154        Enr
6 P1_S003_V4_CD154_ICS_Pre.fcs S003_V4_Pre    S003    V4 CD154        Pre

The "New" column is match with data name.

After then:

> fit = COMPASS(cc, category_filter=NULL, treatment=Visit == "V3",control=Visit == "V1",iterations=100)There are a total of 0 samples from 0 individuals in the 'treatment' group.There are a total of 0 samples from 0 individuals in the 'control' group.Error: Filtering has removed all samples


Thanks for your help.

Best,

Jue

**Comment by gfinak** [comment] 2018-04-19 18:33
The individual_id is not the FCS file, it is the "subject". In your case, "PTID"
the sample_id is the FCS file, in your case  "New"

**Comment by gfinak** [comment] 2018-04-19 18:34
You also have this warning appear: "There appear to be negative intensities in the 'data' supplied."
Look carefully into that, it should not happen.

**Comment by mimisikai** [comment] 2018-04-19 18:45
Yes. I see the warning appears again,

Warning message:In COMPASSContainer(data = ll, counts = counts, meta =
meta, individual_id = "PTID",  :  There appear to be negative
intensities in the 'data' supplied.


May I know what's the reason?

And, I try several different comparisons, always come out with errors:
filtering has removed all samples.

fit = COMPASS(cc, category_filter=NULL, subset = Enrichment=="Enr",
treatment=Visit == "V3",control=Visit ==
"V1",iterations=100)Subsetting has removed 92 of 184 samples.There are
a total of 36 samples from 36 individuals in the 'treatment'
group.There are a total of 37 samples from 37 individuals in the
'control' group.The selection criteria for 'treatment' and 'control'
do not produce paired samples for each individual. The following
individual(s) will be dropped:
	S003_V3_Enr, S005_V3_Enr, S007_V3_Enr, S009_V3_Enr, S027_V3_Enr,
S030_V3_Enr, S033_V3_Enr, S034_V3_Enr, S041_V3_Enr, S042_V3_Enr,
S045_V3_Enr, S047_V3_Enr, S048_V3_Enr, S051_V3_Enr, S054_V3_Enr,
S055_V3_Enr, S056_V3_Enr, S059_V3_Enr, S062_V3_Enr, S063_V3_Enr,
S080_V3_Enr, S087_V3_Enr, S089_V3_Enr, S097_V3_Enr, S099_V3_Enr,
S101_V3_Enr, S102_V3_Enr, S014_V3_Enr, S105_V3_Enr, S108_V3_Enr,
S111_V3_Enr, S113_V3_Enr, S115_V3_Enr, S119_V3_Enr, S120_V3_Enr,
S127_V3_Enr, S003_V1_Enr, S005_V1_Enr, S007_V1_Enr, S009_V1_Enr,
S027_V1_Enr, S030_V1_Enr, S033_V1_Enr, S034_V1_Enr, S035_V1_Enr,
S041_V1_Enr, S042_V1_Enr, S045_V1_Enr, S047_V1_Enr, S048_V1_Enr,
S051_V1_Enr, S054_V1_Enr, S055_V1_Enr, S056_V1_Enr, S059_V1_Enr,
S062_V1_Enr, S063_V1_Enr, S080_V1_Enr, S087_V1_Enr, S089_V1_Enr,
S097_V1_Enr, S099_V1_Enr, S101_V1_Enr, S102_V1_Enr, S104_V1_Enr,
S105_V1_Enr, S108_V1_Enr, S111_V1_Enr, S115_V1_Enr, S119_V1_Enr,
S120_V1_Enr, S123_V1_Enr, S127_V1_EnrError: Filtering has removed all
samples.

**Comment by gfinak** [comment] 2018-04-19 19:13
The negative intensities, are apparently in your `data` object. You'll have to look and see.
Your  COMPASSContainer seems to be in order. The issue is, I think with the COMPASS call.
subset should select both the stimulated and non-stimulated samples. You are also trying to compare visit 3 against visit 1. That's not correct here, the comparison is stimulated against non-stimulated. You would then compare visits after fitting the model.
So, something like this:

`fit = COMPASS(cc, category_filter=NULL, subset = Visit =="V1"|Visit=="V2", treatment= Enrichment=="Enr", control=Enrichment=="Pre", iterations=40000, replications=8)`

**Comment by gfinak** [comment] 2018-04-19 19:13
I updated the comment, should be "V3" not "V2"

**Comment by gfinak** [comment] 2018-04-19 19:14
Once you've fit the model, 
`result_table = scores(fit)` 
will give you something you can plot via boxplots etc.

**Comment by mimisikai** [comment] 2018-04-19 19:25
Still come out with :

> fit = COMPASS(cc, category_filter=NULL, subset = Visit =="V1"|Visit=="V3", treatment= Enrichment=="Enr", control=Enrichment=="Pre", iterations=40000, replications=8)Subsetting has removed 38 of 184 samples.There are a total of 73 samples from 73 individuals in the 'treatment' group.There are a total of 73 samples from 73 individuals in the 'control' group.The selection criteria for 'treatment' and 'control' do not produce paired samples for each individual. The following individual(s) will be dropped:
	S003_V1_Enr, S003_V3_Enr, S005_V3_Enr, S005_V1_Enr, S007_V1_Enr,
S007_V3_Enr, S009_V3_Enr, S009_V1_Enr, S027_V1_Enr, S027_V3_Enr,
S030_V3_Enr, S030_V1_Enr, S033_V3_Enr, S033_V1_Enr, S034_V3_Enr,
S034_V1_Enr, S035_V1_Enr, S041_V3_Enr, S041_V1_Enr, S042_V3_Enr,
S042_V1_Enr, S045_V3_Enr, S045_V1_Enr, S047_V1_Enr, S047_V3_Enr,
S048_V1_Enr, S048_V3_Enr, S051_V1_Enr, S051_V3_Enr, S054_V1_Enr,
S054_V3_Enr, S055_V3_Enr, S055_V1_Enr, S056_V3_Enr, S056_V1_Enr,
S059_V3_Enr, S059_V1_Enr, S062_V1_Enr, S062_V3_Enr, S063_V1_Enr,
S063_V3_Enr, S080_V1_Enr, S080_V3_Enr, S087_V1_Enr, S087_V3_Enr,
S089_V1_Enr, S089_V3_Enr, S097_V1_Enr, S097_V3_Enr, S099_V3_Enr,
S099_V1_Enr, S101_V1_Enr, S101_V3_Enr, S102_V1_Enr, S102_V3_Enr,
S104_V1_Enr, S014_V3_Enr, S105_V1_Enr, S105_V3_Enr, S108_V3_Enr,
S108_V1_Enr, S111_V3_Enr, S111_V1_Enr, S113_V3_Enr, S115_V3_Enr,
S115_V1_Enr, S119_V3_Enr, S119_V1_Enr, S120_V3_Enr, S120_V1_Enr,
S123_V1_Enr, S127_V3_Enr, S127_V1_Enr, S003_V1_Pre, S003_V3_Pre,
S005_V3_Pre, S005_V1_Pre, S007_V1_Pre, S007_V3_Pre, S009_V3_Pre,
S009_V1_Pre, S027_V1_Pre, S027_V3_Pre, S030_V3_Pre, S030_V1_Pre,
S033_V3_Pre, S033_V1_Pre, S034_V3_Pre, S034_V1_Pre, S035_V1_Pre,
S041_V3_Pre, S041_V1_Pre, S042_V3_Pre, S042_V1_Pre, S045_V3_Pre,
S045_V1_Pre, S047_V1_Pre, S047_V3_Pre, S048_V1_Pre, S048_V3_Pre,
S051_V1_Pre, S051_V3_Pre, S054_V1_Pre, S054_V3_Pre, S055_V3_Pre,
S055_V1_Pre, S056_V3_Pre, S056_V1_Pre, S059_V3_Pre, S059_V1_Pre,
S062_V1_Pre, S062_V3_Pre, S063_V1_Pre, S063_V3_Pre, S080_V1_Pre,
S080_V3_Pre, S087_V1_Pre, S087_V3_Pre, S089_V1_Pre, S089_V3_Pre,
S097_V1_Pre, S097_V3_Pre, S099_V3_Pre, S099_V1_Pre, S101_V1_Pre,
S101_V3_Pre, S102_V1_Pre, S102_V3_Pre, S104_V1_Pre, S014_V3_Pre,
S105_V1_Pre, S105_V3_Pre, S108_V3_Pre, S108_V1_Pre, S111_V3_Pre,
S111_V1_Pre, S113_V3_Pre, S115_V3_Pre, S115_V1_Pre, S119_V3_Pre,
S119_V1_Pre, S120_V3_Pre, S120_V1_Pre, S123_V1_Pre, S127_V3_Pre,
S127_V1_PreError: Filtering has removed all samples.

**Comment by gfinak** [comment] 2018-04-19 19:27
your `individual_id` is a concatenation of the PTID_Visit_Enrichment
These are unique for samples, but not for individuals.
Can you show your code for constructing the COMPASS container?

**Comment by gfinak** [comment] 2018-04-19 19:28
Use 
\`\`\` 
code
\`\`\`

to get nicely formatted code

**Comment by gfinak** [comment] 2018-04-19 19:31
I see it, I misread your metadata table. Your `individual_id` should be `"Subject"`

**Comment by mimisikai** [comment] 2018-04-19 20:40
Thanks, Greg. That works and ongoing. I think the most confusion part is
how to interpret the "sample_id" and "individual_id". I assume, the
individual ID is equal to patient ID, and sample ID is equal to patient +
treatment + timepoint et al. Is that right?
I think if you can clarify these purposes of two parameters in the COMPASS,
I guess we may be understand better and would figure out how to adapt our
data to fill the COMPASS data format. Thanks.

**Comment by mimisikai** [comment] 2018-04-20 19:48
Hi Greg. Can you provide the all parameters in the plot() function? I want
to customize the figure as your shown in the NB paper. I've checked the
supplement web links for those figures but there are all expired or
invalided. If you can share the code of those figures, that'll be great
helpful. Thanks.

**Comment by gfinak** [comment] 2018-04-20 20:30
Can you send the plot code you are running, and an example of what you're trying to achieve? There was nothing fancy about the plots in the paper, just calling `plot()` on the COMPASSResult with some variable annotations from the metadata, most of the defaults should apply.

**Comment by mimisikai** [comment] 2018-04-20 21:15
Yes. I just wonder how to set the annotations. my code is plot(fit), the
give me back the basic heatmap plot.

**Comment by gfinak** [comment] 2018-04-20 22:58
Simply something like: `plot(fit,"Visit")`

**Comment by mimisikai** [comment] 2018-04-20 23:52
In my metadata, I have bunch of parameters, "Subject","Visit", "Assay" et
al. But in the scores result table, I don't know how and why, only "Assay"
parameter included. So how can I include "Visit" instead of "Assay"?

**Comment by gfinak** [comment] 2018-04-21 00:40
Does `fit$data$meta` have the columns you need?

**Comment by gfinak** [comment] 2018-04-21 00:46
Ah.. I know the problem, I steered you wrong. When the model was fit, it probably aggregated the subjects across Visits,  because the individual_id was "subject" (which was my fault). 
To do what you are trying to do (fit multiple visits simultaneously), you need to create a new subject id column (almost like what you did initially), and that subject id column should be a concatenation of Subject_Visit, (as opposed to just Subject which it is now, or Subject_Visit_Stimulation as you had initially).
That will treat each subject x visit combination as a unique individual and will generate a polyfunctionality score for each, and Visit will appear in your scores table. Sorry about the mix up. You'll have to refit your model. You may specify 100 iterations and 1 replicate just to see if the result is formatted properly before continuing with a full run.

**Comment by mimisikai** [comment] 2018-04-23 16:55
Thanks, Greg! That works!
I think it's the last question. Due to inconsistency on the marker names,
my code to read the single cell expression was like this:

ll = getSingleCellExpression(gs_man,nodes, map = list("CD154/IL10" =
"Comp-PE-Cy7-A", "CD154/IL13" = "Comp-PerCP-Cy5-5-A",
                                                      "CD154/IL17A" =
"Comp-APC-Cy7-A","CD154/IL4" = "Comp-FITC-A",
                                                      "CD154/IL5" =
"Comp-Alexa Fluor 647-A","CD154/IFNG" = "Comp-Alexa Fluor 700-A"), swap =
TRUE)

So, the final plot shows the channel names instead of cytokine names. I
wonder how can have cytokine names in the figure. Definitely, I can
photoshop the figure eventually, but I still wanna know how to change it in
script.

Thanks!

Joe
